version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.20
    environment:
        POSTGRES_DB: digitas_todo
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    restart: always
    ports:
        - 5432:5432
  b3digitas.todo.api:
    image: ${DOCKER_REGISTRY-}b3digitastodoapi
    build:
      context: .
      dockerfile: B3Digitas.Todo.Api/Dockerfile
    depends_on:
        - postgres
    ports:
        - 8080:8080
        - 8081:8081 
